export const ADD_COMPARE_HOUSE = 'ADD_COMPARE_HOUSE';
export const EMPTY_COMPARE_HOUSES = 'EMPTY_COMPARE_HOUSES';
export const HOME_MAP_BOUND_CHANGED = 'HOME_MAP_BOUND_CHANGED';
export const HOME_DISPLAY_HOUSES_CHANGED = 'HOME_DISPLAY_HOUSES_CHANGED';
export const HOME_MAP_FOCUSED_MARKER_CHANGED = 'HOME_MAP_FOCUSED_MARKER_CHANGED';